### PR TITLE
A few more changes

### PR DESCRIPTION
**Pull request by jonesmartins**
I messed up somewhere, which explains the size of this PR. Next time, I'll create an issue before a PR.

- Created `npm run playground` command;
- Created two files in the test directory: `run-corpus.sh` and `run-corpus.ps1`, so I could run corpus tests on Linux in parallel;
- Changed `README.md` instructions to sync with past commits + a few formatting changes;

### CODE REVIEW

**Comment by ahelwer** [comment]
The formatting changes to the README seem to have made every sentence its own paragraph?

**Comment by jonesmartins** [comment]
Oh, that's true. I formatted it manually according to markdownlint on VSCode, but that wasn't intentional. Is it possible to remove README.md from this PR?

**Comment by ahelwer** [comment]
Yes, you can do that. You will also need to rebase your changes on top of your previous PR's changes.

**Comment by jonesmartins** [comment]
I messed up so much I decided to start over and start correctly. heh...

**Pull request closed without merging**
