### PR TITLE
Change unit test instruction

### PR DESCRIPTION
**Pull request by jonesmartins**
No need for `node_modules/bin` to be in PATH. Since `npx` comes with `npm`, we can use `npx tree-sitter test`.

### CODE REVIEW

**Comment by ahelwer** [comment]
Oh neat! Didn't know about this, thanks. Perhaps also change the CI workflows to use it?

**Comment by jonesmartins** [comment]
Sure. Totally forgout about the CI. I'll have a look

**Comment by jonesmartins** [comment]
`npm test`, `npx tree-sitter build-wasm` and `npx tree-sitter playground` are all working locally. I'm not sure about the CI yet.

I could also define `npm playground` as `npx tree-sitter build-wasm; npx tree-sitter playground` or, at least, `npm build-wasm` and `npm playground`, if you want.

**Comment by ahelwer** [comment]
Great, thanks!

**Pull request merged**
